export const SCHEDULE_NEXT_MONTH = "SCHEDULE_NEXT_MONTH";

export const SCHEDULE_PREV_MONTH = "SCHEDULE_PREV_MONTH";

export const DELETE_EVENT = "DELETE_EVENT";

export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";

export const CREATE_EVENT = "CREATE_EVENT";

export const REVERSE_CHECKED = "REVERSE_CHECKED";
