export const SCHEDULE_NEXT_MONTH = "SCHEDULE_NEXT_MONTH";

export const SCHEDULE_PREV_MONTH = "SCHEDULE_PREV_MONTH";

export const DELETE_EVENT = "DELETE_EVENT";

export const DELETE_ALL_EVENTS = "DELETE_ALL_EVENTS";

export const CREATE_EVENT = "CREATE_EVENT";

export const REVERSE_CHECKED = "REVERSE_CHECKED";

export const OPEN_DIALOG = "TOGGLE_DIALOG";

export const CLOSE_DIALOG = "CLOSE_DIALOG";

export const OPEN_DETAIL = "OPEN_DETAIL";

export const CLOSE_DETAIL = "CLOSE_DETAIL";

export const SET_EVENTS_TO_ITEM = "SET_EVENTS_TO_ITEM";
